<?xml version="1.0" ?>
<robot name="turtlebot3_waffle" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find turtlebot3_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find aslam_bringup)/launch/turtlebot3_simulation/urdf/turtlebot3_waffle.gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>
  
  <xacro:property name="telescopic_extension_length" value="0.15"/>
  
  
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/bases/waffle_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
<!--
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="0.266 0.266 0.094"/>
      </geometry>
-->
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="0.266 0.266 0.094"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <mass value="1.3729096e+00"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
               iyy="8.6195418e-03" iyz="-3.5422299e-06"
               izz="1.4612727e-02" />
<!--
      <mass value="1"/>
      <inertia ixx="0.006633" ixy="0.0" ixz="0.0"
               iyy="0.006633" iyz="0.0"
               izz="0.011793" />
-->
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
<!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
-->
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
    </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
<!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
-->
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
    </inertial>
  </link>

  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.128 -0.144 0.023" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
<!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
-->
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.029" />
      <inertia ixx="0.000008678" ixy="0.0" ixz="0.0"
               iyy="0.000008678" iyz="0.0"
               izz="0.00001579" />
    </inertial>
  </link>

  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.128 0.144 0.023" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
<!--
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
-->
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.029" />
      <inertia ixx="0.000008678" ixy="0.0" ixz="0.0"
               iyy="0.000008678" iyz="0.0"
               izz="0.00001579" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.064 0 0.122" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
<!--
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
-->
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="front_camera_joint" type="fixed">
    <origin xyz="0.064 -0.065 0.094" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="front_camera_link"/>
  </joint>

  <link name="front_camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
       <mesh filename="package://turtlebot3_description/meshes/sensors/r200.dae" />
      </geometry>
<!--
      <origin xyz="0.0 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.0038 0.1016 0.0096"/>
      </geometry>
-->
    </visual>
    
    <collision>
      <origin xyz="0.0 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.0038 0.1016 0.0096"/>
      </geometry>
    </collision>

    <!-- This inertial field needs doesn't contain reliable data!! -->
   <inertial>
      <mass value="0.05" />
      <origin xyz="0.0 0.065 0.007" rpy="0 0 0"/>
      <inertia ixx="0.000043395"  ixy="0.0" ixz="0.0"
               iyy="0.0000004442" iyz="0.0"
               izz="0.00004307" />
    </inertial>
  </link>

  <joint name="front_camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="front_camera_link"/>
    <child link="front_camera_rgb_frame"/>
  </joint>
  <link name="front_camera_rgb_frame"/>

  <joint name="front_camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="front_camera_rgb_frame"/>
    <child link="front_camera_rgb_optical_frame"/>
  </joint>
  <link name="front_camera_rgb_optical_frame"/>

  <joint name="front_camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="front_camera_link"/>
    <child link="front_camera_depth_frame"/>
  </joint>
  <link name="front_camera_depth_frame"/>

  <joint name="front_camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="front_camera_depth_frame"/>
    <child link="front_camera_depth_optical_frame"/>
  </joint>
  <link name="front_camera_depth_optical_frame"/>
  
<!-- Added by Iker -->
  <!-- Pan movement -->
  <joint name="telescopic_arm_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="telescopic_arm_base_link"/>
    <origin rpy="0 -1.57 0" xyz="-0.064 0 0"/>
  </joint>
  
  <link name="telescopic_arm_base_link">
    <visual>
      <geometry>
        <cylinder length="0.001" radius=".01"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="0 0 0"/>
      <material name="Gray">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="0.001" radius=".01"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0000025083" ixy="0.0" ixz="0.0"
               iyy="0.0000025083" iyz="0.0"
               izz="0.000005" />
    </inertial>
  </link>
  
  <joint name="telescopic_arm_continuous_joint" type="continuous">
    <parent link="telescopic_arm_base_link"/>
    <child link="telescopic_arm_extension_base_link"/>
    <origin rpy="0 0 0" xyz="0.0005 0 0"/>
    <limit effort="0.1" velocity="0.1"/>
  </joint>
  
  <link name="telescopic_arm_extension_base_link">
    <visual>
      <geometry>
<!--
        <cylinder length="${telescopic_extension_length}" radius=".01"/>
-->
        <mesh filename="package://aslam_bringup/launch/turtlebot3_simulation/meshes/cylinder_150_10_2.stl"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
      <material name="Gray">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="${telescopic_extension_length}" radius=".01"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.1" />
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
      <inertia ixx="0.00019" ixy="0.0" ixz="0.0"
               iyy="0.00019" iyz="0.0"
               izz="0.000005" />
    </inertial>
  </link>
  
  <!-- Telescopic arm -->
  <joint name="telescopic_arm_extension_1_joint" type="prismatic">
    <parent link="telescopic_arm_extension_base_link"/>
    <child link="telescopic_arm_extension_1_link"/>
    <limit effort="30" lower="0" upper="0.15" velocity="0.05"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
  </joint>

  <link name="telescopic_arm_extension_1_link">
    <visual>
      <geometry>
<!--
        <cylinder length="${telescopic_extension_length}" radius=".008"/>
-->
        <mesh filename="package://aslam_bringup/launch/turtlebot3_simulation/meshes/cylinder_150_08_2.stl"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
      <material name="Gray">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="${telescopic_extension_length}" radius=".008"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.08" />
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
      <inertia ixx="0.00015128" ixy="0.0" ixz="0.0"
               iyy="0.00015128" iyz="0.0"
               izz="0.00000256" />
    </inertial>
  </link>
  
  <joint name="telescopic_arm_extension_2_joint" type="prismatic">
    <parent link="telescopic_arm_extension_1_link"/>
    <child link="telescopic_arm_extension_2_link"/>
    <limit effort="30" lower="0" upper="0.15" velocity="0.05"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mimic joint="telescopic_arm_extension_1_joint"/>
  </joint>

  <link name="telescopic_arm_extension_2_link">
    <visual>
      <geometry>
<!--
        <cylinder length="${telescopic_extension_length}" radius=".006"/>
-->
        <mesh filename="package://aslam_bringup/launch/turtlebot3_simulation/meshes/cylinder_150_06_2.stl"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
      <material name="Gray">
        <color rgba=".4 .4 .4 1"/>
      </material>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="${telescopic_extension_length}" radius=".006"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.06" />
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
      <inertia ixx="0.00011304" ixy="0.0" ixz="0.0"
               iyy="0.00011304" iyz="0.0"
               izz="0.00000108" />
    </inertial>
  </link>
  
  <joint name="telescopic_arm_extension_3_joint" type="prismatic">
    <parent link="telescopic_arm_extension_2_link"/>
    <child link="telescopic_arm_extension_3_link"/>
    <limit effort="30" lower="0" upper="0.15" velocity="0.05"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mimic joint="telescopic_arm_extension_2_joint"/>
  </joint>

  <link name="telescopic_arm_extension_3_link">
    <visual>
      <geometry>
        <cylinder length="${telescopic_extension_length}" radius=".004"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
      <material name="Gray">
        <color rgba=".6 .6 .6 1"/>
      </material>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="${telescopic_extension_length}" radius=".004"/>
      </geometry>
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.04" />
      <origin rpy="0 1.57 0 " xyz="${telescopic_extension_length/2} 0 0"/>
      <inertia ixx="0.00007516" ixy="0.0" ixz="0.0"
               iyy="0.00007516" iyz="0.0"
               izz="0.00000032" />
    </inertial>
  </link>
  
  <!-- Tilt camera -->
  <joint name="top_camera_tilt_joint" type="revolute">
    <parent link="telescopic_arm_extension_3_link"/>
    <child link="top_camera_tilt_link"/>
    <origin xyz="${telescopic_extension_length+0.004} 0 0" rpy="0 1.57 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="0.1" lower="-0.79" upper="0.79" velocity="0.5"/>
  </joint>
  
  <link name="top_camera_tilt_link">
    <visual>
      <geometry>
        <cylinder length="0.04" radius=".004"/>
      </geometry>
      <origin rpy="-1.57 0 0 " xyz="0 0 0"/>
      <material name="Gray">
        <color rgba=".8 .8 .9 1"/>
      </material>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="0.04" radius=".004"/>
      </geometry>
      <origin rpy="-1.57 0 0 " xyz="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="0.05" />
      <origin rpy="-1.57 0 0 " xyz="0 0 0"/>
      <inertia ixx="0.000006867" ixy="0.0" ixz="0.0"
               iyy="0.000006867" iyz="0.0"
               izz="0.0000004" />
    </inertial>
  </link>
  
  <joint name="top_camera_joint" type="fixed">
    <origin xyz="0.0 0.0 0.004" rpy="0 0 0"/>
    <parent link="top_camera_tilt_link"/>
    <child link="top_camera_link"/>
  </joint>
  
  <link name="top_camera_link">
    <visual>
      <origin xyz="0 -0.065 0" rpy="1.57 0 1.57"/>
      <geometry>
       <mesh filename="package://turtlebot3_description/meshes/sensors/r200.dae" />
      </geometry>
<!--
      <origin xyz="0.0 0.0 0.0048" rpy="0 0 0"/>
      <geometry>
        <box size="0.0038 0.1016 0.0096"/>
      </geometry>
-->
    </visual>
    
    <collision>
      <origin xyz="0.0 0.0 0.0048" rpy="0 0 0"/>
      <geometry>
        <box size="0.0038 0.1016 0.0096"/>
      </geometry>
    </collision>

    <!-- This inertial field needs doesn't contain reliable data!! -->
   <inertial>
      <mass value="0.05" />
      <origin xyz="0.0 0.0 0.010" rpy="0 0 0" />
      <inertia ixx="0.000043395"  ixy="0.0" ixz="0.0"
               iyy="0.0000004442" iyz="0.0"
               izz="0.00004307" />
    </inertial>
  </link>

  <joint name="top_camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="top_camera_link"/>
    <child link="top_camera_rgb_frame"/>
  </joint>
  <link name="top_camera_rgb_frame"/>

  <joint name="top_camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="top_camera_rgb_frame"/>
    <child link="top_camera_rgb_optical_frame"/>
  </joint>
  <link name="top_camera_rgb_optical_frame"/>

  <joint name="top_camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="top_camera_link"/>
    <child link="top_camera_depth_frame"/>
  </joint>
  <link name="top_camera_depth_frame"/>

  <joint name="top_camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="top_camera_depth_frame"/>
    <child link="top_camera_depth_optical_frame"/>
  </joint>
  <link name="top_camera_depth_optical_frame"/>
  
</robot>
