# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
telescopic_arm_continuous_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: telescopic_arm_continuous_joint
  pid: {p: 1.0, i: 10.0, d: 00.0}

telescopic_arm_extension_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: telescopic_arm_extension_1_joint
  pid: {p: 100.0, i: 10.0, d: 10.0}

telescopic_arm_extension_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: telescopic_arm_extension_2_joint
  pid: {p: 100.0, i: 10.0, d: 10.0}

telescopic_arm_extension_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: telescopic_arm_extension_3_joint
  pid: {p: 100.0, i: 10.0, d: 10.0}

top_camera_tilt_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: top_camera_tilt_joint
  pid: {p: 10.0, i: 1.0, d: 0.0}
